lab50: 
  window:
    - editor
    - readme
    - terminal
    - browser
  files:
    - !include myPage.html
    - !exclude "README.md"
 
  submit50:
    files: &files
      - !exclude "*"
      - !require myPage.html
