lab50:
  files:
    - !exclude README.md
    - !include fahrenheit.c
    - !include pseudocode.txt

submit50:
  files: &files
    - !exclude "*"
    - !require pseudocode.txt
    - !require fahrenheit.c
